export const bookingMapping = {
  Booking: "Booking",
  FechaReserva: "FechaReserva",
  SCO: "SCO",
  IdCampanha: "IdCampanha",
  IdNaviera: "IdNaviera",
  NAVE: "Nave",
  VIAJE: "Viaje",
  Rumbo: "Rumbo",
  ETA: "ETA",
  EtaSemana: "ETASemana",
  ETD: "ETD",
  EtdSemana: "ETDSemana",
  TiempoTransito: "TiempoTransito",
  IdPuertoEmbarque: "IdPuertoEmbarque",
  IdPuertoDestino: "IdPuertoDestino",
  Transbordo: "Transbordo",
  "TransbordoM1P (transbordo en mas de un puerto)": "TransbordoM1P",
  "TransbordoObservaciones (cuando transbordo en más de un puerto en 1)": "TransbordoObservaciones",
  IdPuertoTransbordo: "IdPuertoTransbordo",
  Producto: "IdProducto",
  "Atmosfera Controlada": "AtmosferaControlada",
  O2: "O2",
  CO2: "CO2",
  Humedad: "Humedad",
  HumedadPorcentaje: "HumedadPorcentaje",
  Ventilacion: "Ventilacion",
  CbmHr: "CbmHr",
  ColdTreatment: "ColdTreatment",
  Refrigerado: "Refrigerado",
  Temperatura: "Temperatura",
  IdTecnologia: "IdTecnologia",
  ObsCondicionFlete: "ObsCondicionFlete",
  IdLugarEmisionBL: "IdLugarEmisionBL",
  ObsLugarEmisionBL: "ObsLugarEmisionBL",
  IdCondicionFlete: "IdCondicionFlete",
  Customer: "Customer",
  IdProveedorFlete: "IdProveedorFlete",
  IdIncoterm: "IdIcoterm",
  CantidadContenedorSolicitados: "CantidadContenedorSolicitados",
  CantidadContenedorAsignados: "CantidadContenedorAsignados",
  LugarPagoBL: "LugarPagoBL"
};
